### PR TITLE
Add support for image confetti

### PR DESCRIPTION
**Pull request by jasonappah**
This PR adds support for image confetti. `addConfetti` now has a new optional property called `images`, which holds a list of objects with the following format:
```ts
interface IImage {
  src: CanvasImageSource,
  width?: number,
  height?: number,
```

### CODE REVIEW

**Comment by loonywizard** [comment]
@jasonappah hi! thanks a lot for your contribution

I see that this PR changes a lot of code-style formatting. I believe this is due to the reason I have not setup any linters yet 😁 I will try to find time to setup some Prettier or ESLint for the project and then I can review this PR

Also I tried to run the demo and I see that Image confettis do not rotate as normal confettis or emoji confettis do

**Comment by jasonappah** [comment]
Ah whoops, I completely forgot about the formatting changes. Whenever you have linting setup, let me know and I'll run it on my fork. I also forgot to get the images rotating, will do in a sec :)

**Comment by loonywizard** [comment]
I have just added `lint-fix` script to package.json and run it on the codebase #43 

I will try to add `lint-fix` as pre-commit hook and later I will add this to CI (which I don't have at the moment), but for now you can just manually run `lint-fix` before git push

**Comment by jasonappah** [comment]
everything should be fixed now :) @loonywizard

**Comment by fredrikj31** [comment]
Is there a reason why this pull request got closed? Is this not a feature that js-confetti will support?

**Comment by darklight9811** [comment]
suddenly it died off :c

**Comment by jasonappah** [comment]
Happy to recreate the PR if this is something people are interested in - totally forgot about this PR haha

**Comment by darklight9811** [comment]
I support this idea

**Pull request closed without merging**
